### ISSUE TITLE
Issues with footnotes 3, 4, 5 ,6 ,7 and kindle paperwhite

### ISSUE THREAD

**Issue by atrahhdis** [atrahhdis/alohadharma#1]
I am opening this issue mainly asking for some feedback from kindle users. 

Although most probably there's a software issue with my kindle and the e-book is ok, I would really appreciated it if I got some feedback from kindle users regarding footnotes 2, 3, 4, 5, 6, 7 and if the footnote pop up appears when you click on them on the text.

Thank you in advance.
mv

**Comment by mahasivipassana** [comment]
I tested the file with kindle previewer and it seems to be functioning OK. 

However the feedback from a user with a kindle voyage remains the same: footnotes 2, 3, 4, 5, 6 and 7 are not functioning as they should.

Just to give some further information on how these e-books are created:

- md to epub with pandoc
- epub editing with calibre (metatada etc)
- epub to azw3 with calibre
- additional soft hyphenation with hyphenate this plugin

**Comment by atrahhdis** [comment]
The issue is finally fixed.

AZW3 file is now created using a MOBI file:

EPUB --> MOBI
MOBI --> AZW3

Previous conversion was:
- EPUB --> MOBI
- EPUB -->AZW3
